- name: 'Update and Install packages for web servers'
  hosts: web_servers
  become: yes
  become_method: sudo
  vars:
    packages:
      - apache2
      - wget
      - htop
      - curl
      - firewalld
  
  tasks:
    - name: 'Update packages'
      shell: sudo apt update -y
  
    - name: 'Upgrade software'
      shell: sudo apt upgrade -y

    - name: 'Clean up'
      shell: sudo apt autoremove -y

    - name: 'Install required packages'
      apt:
        name: '{{ packages }}'
        state: present
	
    - name: 'Check apache status'
      shell: sudo systemctl status apache2
      register: service_result
    
    - name: 'Print apache status'
      debug:
	msg: '{{ service_result.stdout }}'

    - name: 'Force start apache webserver'
      service:
	name: apache2
	state: started


