- name: 'Update and Install packages for nfs servers'
  hosts: nfs 
  become: yes
  become_method: sudo
  vars:
    packages:
      - nfs-kernel-server
      - wget
      - htop
      - curl
      - firewalld
  
  tasks:
    - name: 'Update packages'
      shell: sudo apt update -y
  
    - name: 'Upgrade software'
      shell: sudo apt upgrade -y

    - name: 'Clean up'
      shell: sudo apt autoremove -y

    - name: 'Install required packages'
      apt:
        name: '{{ packages }}'
        state: present
    
    - name: 'Check nfs status'
      shell: sudo systemctl status nfs-server-kernel
      register: service_result
      
    - name: 'Print nfs status'
      debug:
        msg: '{{ service_result.stdout }}'

    - name: 'Force start nfs'
      service:
	name: nfs-kernel-server
	state: started
