- name: 'Update and Install packages for web servers'
  hosts: proxies 
  become: yes
  become_method: sudo
  vars:
    packages:
      - haproxy
      - wget
      - htop
      - curl
      - firewalld
  
  tasks:
    - name: 'Update packages'
      shell: sudo apt update -y
  
    - name: 'Upgrade software'
      shell: sudo apt upgrade -y

    - name: 'Clean up'
      shell: sudo apt autoremove -y

    - name: 'Install required packages'
      apt:
        name: '{{ packages }}'
        state: present
    
    - name: 'Check haproxy status'
      shell: sudo systemctl haproxy
      register: service_result
      
    - name: 'Print haproxy status'
      debug:
        msg: '{{ service_result.stdout }}'

    - name: 'Force start haproxy'
      service:
	name: haproxy
	state: started
